//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMySql.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class houserent
    {
        public string price { get; set; }
        public string whole { get; set; }
        public string rent { get; set; }
        public string area { get; set; }
        public string contact { get; set; }
        public string phone { get; set; }
        public string description { get; set; }
        public int id { get; set; }
    }
}
